#!/bin/bash

URL="https://github.com/nginxinc/docker-nginx/archive/refs/heads/master.zip"
SAVE_PATH="/users/thomas.wilkinson/desktop/dissertation"
DOCKER_PATH="/users/thomas.wilkinson/desktop/dissertation/master"
IMAGE_NAME="my_image"

#echo "please enter URL"
#read -r URL

#echo "please enter save path"
#read -r SAVE_PATH

#echo "please enter Docker path"
#read -r DOCKER_PATH

#echo "please enter image name for new image"
#read -r IMAGE_NAME

function check_url_regex() {
URL_CHECK_REGEX='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
if [[ "$URL" =~ ${URL_CHECK_REGEX} ]]; then
    echo "$URL is valid."
else
    echo "$URL is not valid."
fi
}


function check_path_regex() {
PATH_CHECK_REGEX='^(\/[^\/]*)+\/?$'
if [[ "$SAVE_PATH" =~ ${PATH_CHECK_REGEX} ]]; then
    echo "$SAVE_PATH is valid"
    FOLDER=$(dirname "$SAVE_PATH")
    if [[ -d "$FOLDER" ]]; then
        echo "Folder $FOLDER exists"
    else
        echo "Folder $FOLDER doesn't exist, creating it"
        mkdir -p -v "$FOLDER"
        if [ -f "$FOLDER" ]; then
            echo "created $FOLDER"
        else
            echo "failed to create $FOLDER"
            exit 1
          fi
      fi
  else
      echo "$SAVE_PATH is an invalid path."
      exit 1
fi
}

check_url_regex
check_path_regex

function private_download() {
    if [ "$(command -v wget)" ]; then
        echo "$URL wget installed, downloading using wget"
        wget $SAVE_PATH $URL | tar -xz
    elif [ "$(command -v curl)" ]; then
          echo "curl installed, download using curl"
          cd "$SAVE_PATH" && curl -LO "$URL" || exit 1
          unzip "$DOCKER_PATH" || exit 1
    else
        echo "Failed to find wget or curl"
        exit 1
    fi
}

private_download

#echo "please enter file path to dockerfile"
#read -r "DOCKER_FILE"

DOCKER_FILE="/users/thomas.wilkinson/desktop/dissertation/docker-nginx-master/stable/debian"

function docker_create() {
    if [ "$(command docker ps)" ]; then
        echo "Docker is running"
        cd "$SAVE_PATH" || exit 1
        #/usr/local/bin/docker import "$DOCKER_PATH" "$IMAGE_NAME" | 
        /usr/local/bin/docker build "$DOCKER_FILE" || exit 1
         #| /usr/local/bin/docker run "$IMAGE_NAME" || exit 1
    else 
        echo "Docker is not running or not installed"
        exit 1
    fi
}

docker_create

echo "please enter the repo location for Kubernetes"
read -r K8_PATH

echo "please enter file name for pod or deployment creation"
read -r FILE_POD


function Kubernetes_create() {
    if [ "$(command kubectl version --output=yaml)" ]; then
        echo "Kubernetes is installed"
        cd "$K8_PATH" || exit 1
       kubectl apply -f "$FILE_POD"
    else
        echo "Kubernetes pod or deployment not found"
        exit 1
    fi

}

Kubernetes_create

echo "please provide the deployment or pod name to be patched"
read -r Deployment


function Kubernetes_patch() {
    if [ "$(command kubectl get pods)" ]; then
        echo "Pod found"
        cd "$K8_PATH" || exit 1
        #kubectl patch deployment "$Deployment" --patch-file "$FILE_NAME" || kubectl patch pod "$Deployment" --patch-file "$FILE_NAME"
        kubectl patch deployment "$Deployment" --type='json' -p='[{"op": "replace", "path": "/spec/containers/name/image", "value":"$IMAGE_NAME"}]' || kubectl patch deployment "$Deployment" --type='json' -p='[{"op": "replace", "path": "/spec/containers/name/image", "value":"$IMAGE_NAME"}]'
    else
        echo "Pod not found"
        kubectl delete pod "$Deployment" || kubectl delete deployment "$Deployment"
        echo "Pod or deployment deleted"
        exit 1
    fi
}

Kubernetes_patch


function private_validate() {
  if [ -f "$SAVE_PATH" ]; then
      echo "File Downloaded."
  else
      echo "Failed to download"
      exit 1
  fi
 }





 