apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    project: 'DissertationProject'
spec:
  containers:
    - name: container-1
      image: nginx:1.14.2
      resources:
        requests:
          memory: "10Mi"
          cpu: "250m"
    

