apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 5
  selector:
    matchLabels:
      project: 
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        project: 
    spec: 
      containers:
      - name:
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        image: 